language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install .
# command to run tests, e.g. python setup.py test
script:  export LINO_CACHE_ROOT=$(TRAVIS_BUILD_DIR) ; fab initdb test

# TRAVIS_BUILD_DIR  The absolute path to the directory where the repository being built has been copied on the worker.

env: =postgres